# https://developers.cloudflare.com/workers/wrangler/ci-cd/
name: Deploy API

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['db/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: pnpm
          workingDirectory: api
      - run: echo "🎉 API successfuly finished!"
