name: Deploy API

on:
  push:
    branches: ['main']
    paths: ['folder/**']

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    name: Deploy API to Cloudfare Workers
    steps:
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: api
          args: publish
      - run: echo "🎉 API successfuly finished!"
