name: Generate Lighthouse Badges
on:
  deployment:
  workflow_dispatch:
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Generate Badges
        run: npx lighthouse-badges --urls https://octagon-api.com/ https://octagon-api.com/division/ -o test_results
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: octogon-api-bot
          author_email: bot@octagon-api.com
          message: '[Bot] Update Lighthouse badges'
          add: 'test_results'
          push: true
          branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
