name: Lighthouse Badge Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 4'

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Run Lighthouse Badge Generator
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true
      - run: |
          npm run lighthouse
          git config user.name octagon-api
          git add -A 
          git commit -am "[BOT] Update Octagon API database"
          git push origin main
      - run: echo "🎉 Task finished!"
