name: GitHub Activity

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Update README with recent repository activity

    steps:
      - uses: actions/checkout@v3
      - uses: Readme-Workflows/recent-activity@2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: '[Bot] Update README with recent activity'
