name: Octogon Scraper

on:
  workflow_dispatch:

  schedule:
    - cron: '0 4 * * 4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true
      - run: |
          npm run scrape
          git config user.name octogon-api
          git add -A 
          git commit -am "[BOT] Update Octogon API database"
          git push origin main
      - run: echo "🎉 Task finished!"
