name: Test action

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 4'

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Run complete scraper
    steps:
      - run: echo "${{ github.ref_name }}"
      - run: |
          git config user.name octagon-api
          git add -A 
          git commit -am "[BOT] Update Octagon API database"
          git push origin ${{ github.ref_name }}
      - run: echo "🎉 Task finished!"
